# GenLayer test networks. `gltest tests/integration -v --network <name>`
networks:
  default: localnet
  localnet:
    url: http://127.0.0.1:4000/api
  studionet:
    url: https://studio.genlayer.com/api
  testnet_bradbury:
    url: https://rpc.genlayer.com/api
    accounts:
      - "${ACCOUNT_PRIVATE_KEY_1}"
paths:
  contracts: contracts
  artifacts: artifacts
